#pragma once

#include "../tools/flag.hpp"

constexpr Flag FLAG_HUD_ALLOWED = Flag(0xD403, 6);
constexpr Flag FLAG_SEPTIMUS_WAKE_UP_TALKING_ABOUT_RONAN = Flag(0xD358, 0);

constexpr Flag FLAG_SYBILL_HOLY_SWORD_VISION_1 = Flag(0xD3F3, 6);
constexpr Flag FLAG_SYBILL_HOLY_SWORD_VISION_2 = Flag(0xD3F3, 5);

constexpr Flag FLAG_UNDEGROUND_WATERWAY_OPENED = Flag(0xD370, 4);

constexpr Flag FLAG_REMOVED_TREE_TO_CLIFFS_OF_MADNESS = Flag(0xD35F, 5);
constexpr Flag FLAG_CHANGE_SIGN_TO_CLIFFS_OF_MADNESS = Flag(0xD34F, 3);

constexpr Flag FLAG_CAN_ACTIVATE_MEGALITHS = Flag(0xD3E6, 0);

constexpr Flag FLAG_LEARNED_ABOUT_MERRICK_WANTING_FALCONS = Flag(0xD3E6, 6);
constexpr Flag FLAG_TALKED_WITH_MERRICK = Flag(0xD3E6, 7);
constexpr Flag FLAG_TALKED_WITH_MERRICK_ABOUT_FALCONS = Flag(0xD3E7, 0);
constexpr Flag FLAG_ACCEPTED_MERRICK_DEAL_ABOUT_FALCONS = Flag(0xD3E9, 1);

constexpr Flag FLAG_OPENED_LAKE_SHRINE_EXTERIOR_MAIN_GATE = Flag(0xD3B2, 7);
constexpr Flag FLAG_LAKE_SHRINE_EXTERIOR_RIGHT_GARDEN_BUTTON = Flag(0xD3C1, 7);
constexpr Flag FLAG_LAKE_SHRINE_EXTERIOR_LEFT_GARDEN_BUTTON = Flag(0xD3C2, 0);
constexpr Flag FLAG_LAKE_SHRINE_EXTERIOR_GARDEN_MIDDLE_GATE = Flag(0xD3C2, 6);

constexpr Flag FLAG_LAKE_SHRINE_INTERIOR_MELZAS_INTRO_CUTSCENE_1 = Flag(0xD3B3, 2);
constexpr Flag FLAG_LAKE_SHRINE_INTERIOR_MELZAS_INTRO_CUTSCENE_2 = Flag(0xD3B3, 3);
constexpr Flag FLAG_LAKE_SHRINE_NW_SEAL_BROKEN = Flag(0xD3B3, 4);
constexpr Flag FLAG_LAKE_SHRINE_W_SEAL_BROKEN = Flag(0xD3B3, 5);
constexpr Flag FLAG_LAKE_SHRINE_SW_SEAL_BROKEN = Flag(0xD3B3, 6);
constexpr Flag FLAG_LAKE_SHRINE_SE_SEAL_BROKEN = Flag(0xD3B3, 7);
constexpr Flag FLAG_LAKE_SHRINE_E_SEAL_BROKEN = Flag(0xD3B4, 0);
constexpr Flag FLAG_LAKE_SHRINE_NE_SEAL_BROKEN = Flag(0xD3B4, 1);

constexpr Flag FLAG_CAN_ENTER_LARS_CRYPT = Flag(0xD351, 0);
constexpr Flag FLAG_CAN_PUT_FLOWERS_IN_GRAVEYARD = Flag(0xD351, 1);
constexpr Flag FLAG_CAN_EXIT_LARS_CRYPT = Flag(0xD34E, 0);

constexpr Flag FLAG_MAGYSCAR_WALL_IS_CRACKED = Flag(0xD357, 5);
